const PostList = [
  {
    username: "Testttt",
    userId: "1029384756",
    profilePic: "/src/assets/images/icon.png",
    postType: "text",
    postID: 3,
    postContent: "Lorem Ipsum",
    postTitle: "",
    comments: [
      { user: "test2", time: "1", comment: "testtttt" },
      { user: "Test3", time: "8", comment: "Helooooo" },
    ],
    likes: [],
    dislikes: [],
  },
  {
    username: "hi",
    userId: "1029384755",
    profilePic: "/src/assets/images/icon.png",
    postType: "weather",
    postID: 4,
    postContent: "Lorem Ipsum",
    postTitle: "",
    comments: [
      { user: "test2", time: "1", comment: "testtttt" },
      { user: "Test3", time: "8", comment: "Helooooo" },
    ],
    likes: [],
    dislikes: [],
  },
  {
    username: "hello",
    userId: "1029384754",
    profilePic: "/src/assets/images/icon.png",
    postType: "image",
    postID: 5,
    postContent: "Lorem Ipsum",
    postTitle: "",
    comments: [
      { user: "test2", time: "1", comment: "testtttt" },
      { user: "Test3", time: "8", comment: "Helooooo" },
    ],
    likes: [],
    dislikes: [],
  },
  {
    username: "hoi",
    userId: "1029384753",
    profilePic: "/src/assets/images/icon.png",
    postType: "text",
    postID: 6,
    postContent: "Lorem Ipsum",
    postTitle: "",
    comments: [
      { user: "test2", time: "1", comment: "testtttt" },
      { user: "Test3", time: "8", comment: "Helooooo" },
    ],
    likes: [],
    dislikes: [],
  },
  {
    username: "bye",
    userId: "1029384753",
    profilePic: "/src/assets/images/icon.png",
    postType: "text",
    postID: 7,
    postContent: "Lorem Ipsum",
    postTitle: "",
    comments: [
      { user: "test2", time: "1", comment: "testtttt" },
      { user: "Test3", time: "8", comment: "Helooooo" },
    ],
    likes: [],
    dislikes: [],
  },
  {
    username: "boo",
    userId: "1029384751",
    profilePic: "/src/assets/images/icon.png",
    postType: "weather",
    postID: 8,
    postContent: "Lorem Ipsum",
    postTitle: "",
    comments: [
      { user: "test2", time: "1", comment: "testtttt" },
      { user: "Test3", time: "8", comment: "Helooooo" },
    ],
    likes: [],
    dislikes: [],
  },
  {
    username: "blah",
    userId: "10293847500",
    profilePic: "/src/assets/images/icon.png",
    postType: "image",
    postID: 9,
    postContent: "Lorem Ipsum",
    postTitle: "",
    comments: [
      { user: "test2", time: "1", comment: "testtttt" },
      { user: "Test3", time: "8", comment: "Helooooo" },
    ],
    likes: [],
    dislikes: [],
  },
];

export default PostList;
