const PostList = [
    {
        username: "Testttt",
        userId: "1029384756", 
        profilePic: "src/assets/images/icon.png",
        postType: "weather",
        postContent: "Lorem Ipsum",
        postTitle: "",
        comments: [{user: "test2", time: "1", comment: "testtttt"}, {user: "Test3", time: "8", comment: "Helooooo"}],
        likes: [],
        dislikes: [],
    },
    {
        username: "",
        userId: "", 
        profilePic: "",
        postType: "weather",
        postID: 1,
        postContent: "Lorem Ipsum",
        postTitle: "",
        comments: [{user: "test2", time: "1", comment: "testtttt"}, {user: "Test3", time: "8", comment: "Helooooo"}],
        likes: [],
        dislikes: [],
    },
    {
        username: "",
        userId: "", 
        profilePic: "",
        postType: "weather",
        postID: 1,
        postContent: "Lorem Ipsum",
        postTitle: "",
        comments: [{user: "test2", time: "1", comment: "testtttt"}, {user: "Test3", time: "8", comment: "Helooooo"}],
        likes: [],
        dislikes: [],
    },
    {
        username: "",
        userId: "", 
        profilePic: "",
        postType: "weather",
        postID: 1,
        postContent: "Lorem Ipsum",
        postTitle: "",
        comments: [{user: "test2", time: "1", comment: "testtttt"}, {user: "Test3", time: "8", comment: "Helooooo"}],
        likes: [],
        dislikes: [],
    },
    {
        username: "",
        userId: "", 
        profilePic: "",
        postType: "weather",
        postID: 1,
        postContent: "Lorem Ipsum",
        postTitle: "",
        comments: [{user: "test2", time: "1", comment: "testtttt"}, {user: "Test3", time: "8", comment: "Helooooo"}],
        likes: [],
        dislikes: [],
    },
    {
        username: "",
        userId: "", 
        profilePic: "",
        postType: "weather",
        postID: 1,
        postContent: "Lorem Ipsum",
        postTitle: "",
        comments: [{user: "test2", time: "1", comment: "testtttt"}, {user: "Test3", time: "8", comment: "Helooooo"}],
        likes: [],
        dislikes: [],
    },
    {
        username: "",
        userId: "", 
        profilePic: "",
        postType: "weather",
        postID: 1,
        postContent: "Lorem Ipsum",
        postTitle: "",
        comments: [{user: "test2", time: "1", comment: "testtttt"}, {user: "Test3", time: "8", comment: "Helooooo"}],
        likes: [],
        dislikes: [],
    },
  ];
  
  export default PostList;
  